language: minimal
os: linux
arch: amd64
dist: bionic
branches: 
  except:
    - CI-latest
script:
- cd vice
- ls -l
- sudo apt-get install xa65
- sudo apt-get install autoconf autotools-dev build-essential byacc flex git subversion vim xa65 alien p7zip-full zip texinfo gawk zip unzip yasm dos2unix libglib2.0-dev-bin icoutils
- sudo apt-get install mingw-w64 mingw-w64-tools
- cd build/mingw
- bash ./frankenvice-install.sh
- cd ..
- cd ..
- sudo glib-compile-schemas /usr/x86_64-w64-mingw32/share/glib-2.0/schemas/.
- ./autogen.sh
- cd ..
- mkdir gtk3-win64-build
- cd gtk3-win64-build
- ../vice/configure --enable-native-gtk3ui --host=x86_64-w64-mingw32  --enable-arch=no
- make
- mkdir $TRAVIS_BUILD_DIR/vice/_out/
- cp src/c1541.exe $TRAVIS_BUILD_DIR/vice/_out/
- cp../vice/src/c1541.exe $TRAVIS_BUILD_DIR/vice/_out/
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: 
  - $TRAVIS_BUILD_DIR/vice/_out/c1541
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: master
