language: minimal
os: linux
arch: amd64
dist: bionic
branches: 
  except:
    - CI-latest
script:
- cd vice
- ls -l
- sudo apt-get install xa65
- sudo apt-get install autoconf autotools-dev build-essential byacc flex git subversion vim xa65 alien p7zip-full zip texinfo gawk zip unzip yasm dos2unix libglib2.0-dev-bin icoutils
- sudo apt-get install mingw-w64 mingw-w64-tools
- cd vice/build/mingw
- sudo ./frankenvice-install.sh
- cd ..
- cd ..
- sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-resources /usr/bin/glib-compile-resources
- sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas /usr/bin/glib-compile-schemas
- sudo ln -s /usr/x86_64-w64-mingw32/bin/glib-genmarshal /usr/bin/glib-genmarshal
- sudo ln -s /usr/x86_64-w64-mingw32/bin/glib-mkenums /usr/bin/glib-mkenums
- sudo glib-compile-schemas /usr/x86_64-w64-mingw32/share/glib-2.0/schemas/.
- cd ..
- ./autogen.sh
- cd ..
- mkdir gtk3-win64-build
- cd gtk3-win64-build
- ../vice/configure --enable-native-gtk3ui --host=x86_64-w64-mingw32
- make
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: 
  - $TRAVIS_BUILD_DIR/vice/_out/c1541
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: master
