language: minimal
os: linux
arch: amd64
dist: bionic
branches: 
  except:
    - CI-latest
script:
- cd vice
- ls -l
- sudo apt-get install xa65
- sudo apt-get install libgtk-3-dev
- sudo apt-get install libglew-dev
- ./autogen.sh
- ./configure --enable-native-gtk3ui
- make 
- mkdir _out
- cp src/c1541 _out
- sudo apt-get remove libgtk-3-dev
- sudo apt-get remove libglew-dev
- sudo apt-get install autoconf autotools build-essential byacc flex git subversion vim xa65 alien p7zip-full zip texinfo gawk* zip unzip
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: 
  - $TRAVIS_BUILD_DIR/vice/_out/c1541
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: master
